### ISSUE TITLE
Sobre los System.out.println

### ISSUE THREAD

**Issue by delucas** [TodosLosNombresBuenosEstanOcupados/jrpg#2]
![nfclef0](https://cloud.githubusercontent.com/assets/684051/19620560/9482010c-9856-11e6-800f-0e614b964bc3.gif)

A lo largo de todo el repositorio hay muchos `System.out.println`. Pocas veces hay auténticas razones para tenerlos, y no deberían estar. Remuévanlos.

**Comment by escurragonzalez** [comment]
Se eliminaron todos los `System.out.println`
