### ISSUE TITLE
Sobre los archivos de configuración

### ISSUE THREAD

**Issue by delucas** [TodosLosNombresBuenosEstanOcupados/jrpg#4]
Se prefiere utilizar archivos `.properties`, que Java los levanta con una sola línea de código.
Cambien su `niveles.cfg` por un `niveles.properties`

**Comment by ilandaburu** [comment]
Se modifica la extensión del archivo de los niveles a .properties
Se cierra la issue.

**Comment by delucas** [comment]
Recuerden utilizar el mecanismo adecuado para levantar el archivo cuando lo necesiten.
