### ISSUE TITLE
Sobre las rutas del classpath

### ISSUE THREAD

**Issue by delucas** [TodosLosNombresBuenosEstanOcupados/jrpg#5]
Ciertas rutas del `.classpath` son absolutas a la máquina de uno de ustedes, @escurragonzalez .
Ejemplo, [esta](https://github.com/TodosLosNombresBuenosEstanOcupados/jrpg/commit/da6c2d62b197b641fc24fdb0aff1d92308720ba1#diff-1e05c72a792fea46e8c214c73e17d2f8R8).

Las opciones que sugiero, son las de incluirlos en el repo y utilizar rutas relativas, o incluirlas en el proyecto e ignorarlos en el repositorio.

**Comment by escurragonzalez** [comment]
Se modifico las rutas del  `.classpath` a relativas
